// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as StylesModuleCss from "../styles.module.css";

var styles = StylesModuleCss;

function Bottom(Props) {
  var status = Props.status;
  return React.createElement("div", undefined, React.createElement("p", {
                  style: {
                    textAlign: "center"
                  }
                }, "Just a 2 players tic tac toe game"), React.createElement("h1", {
                  style: {
                    textAlign: "center"
                  }
                }, status), React.createElement("button", {
                  className: styles.restart,
                  onClick: (function (param) {
                      ((window.location.reload()));
                    })
                }, "restart"));
}

var make = Bottom;

export {
  styles ,
  make ,
}
/* styles Not a pure module */
