// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Title(Props) {
  return React.createElement("h1", {
              style: {
                textAlign: "center"
              }
            }, "Name : Peerayu");
}

var make = Title;

export {
  make ,
}
/* react Not a pure module */
