// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Grid from "./components/Grid.bs.js";
import * as Title from "./components/Title.bs.js";
import * as React from "react";
import * as Bottom from "./components/Bottom.bs.js";
import * as StylesModuleCss from "./styles.module.css";

var styles = StylesModuleCss;

function App(Props) {
  var match = React.useState(function () {
        return "Turn X";
      });
  return React.createElement("div", {
              className: styles.App
            }, React.createElement(Title.make, {}), React.createElement(Grid.make, {
                  setStatus: match[1]
                }), React.createElement(Bottom.make, {
                  status: match[0]
                }));
}

var make = App;

export {
  styles ,
  make ,
}
/* styles Not a pure module */
